version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    environment:
      - REDIS_PASSWORD=""
    networks:
      - test
    restart: always
    command: redis-server --appendonly yes
networks:
  test: