version: '3'

services:
  web:
    build:
      context: .
      dockerfile: dockerfile-web
    depends_on:
      - redis
    ports:
      - "18190:8190"
    networks:
      - docker_learn
    tty: true
    restart: on-failure
  redis:
    image: redis:alpine
    ports:
      - "16379:6379"
    volumes:
      - redis_volume:/data
    environment:
      - REDIS_PASSWORD=""
    networks:
      - docker_learn
    restart: always
    command: redis-server --appendonly yes
networks:
  docker_learn:
    driver: bridge
volumes:
  redis_volume: