version: '3'

services:
  web:
    build:
      context: .
    depends_on:
      - redis
    ports:
      - "8190:8190"
    networks:
      docker-learn:
    tty: true
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-volume:/data
    environment:
      - REDIS_PASSWORD=""
    networks:
      - docker-learn
    restart: always
    command: redis-server --appendonly yes
networks:
  docker-learn:
volumes:
  redis-volume: